$axure.loadCurrentPage({
  "url":"animation.html",
  "generationDate":new Date(1668594946558.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e12802d77214f2181f66f1402fd958c",
    "type":"Axure:Page",
    "name":"Animation",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f16f445c757f4d4ba90454e36b406fff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Pristina Oblique', 'Pristina'",
            "fontSize":"72px",
            "fontStyle":"oblique",
            "location":{
              "x":403,
              "y":91},
            "size":{
              "width":538,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4be15ce799c44e3a3068953bd1f5866",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Pristina Oblique', 'Pristina'",
                "fontSize":"72px",
                "fontStyle":"oblique",
                "location":{
                  "x":403,
                  "y":91},
                "size":{
                  "width":538,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaf518e3478b4830aa386bef24173db8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":43,
              "y":250},
            "size":{
              "width":190,
              "height":273}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa14855dba924dc585d5b91d925b1d33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":43,
                  "y":250},
                "size":{
                  "width":190,
                  "height":273}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt9848626/?ref_=fn_al_tt_1 in New Window/Tab",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt9848626/?ref_=fn_al_tt_1",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u18.png"}},
{
          "id":"88c60d993fc1467299f22c8d5ab88052",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "horizontalAlignment":"center",
            "location":{
              "x":40,
              "y":526},
            "size":{
              "width":200,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a09ad3bab7b4ff8ba5f471e16c4c7c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "horizontalAlignment":"center",
                "location":{
                  "x":40,
                  "y":526},
                "size":{
                  "width":200,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"080d8f8e60d24679a603deb6f1af664a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":346,
              "y":528},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9145a021f48472a9963758e8cd9d812",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":346,
                  "y":528},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c0b1e84b1d5422a892502ca98d26a37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":276,
              "y":250},
            "size":{
              "width":190,
              "height":273}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ae34dafda5f4861ac05171e64f3d339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":276,
                  "y":250},
                "size":{
                  "width":190,
                  "height":273}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt13634480/?ref_=fn_al_tt_1 in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt13634480/?ref_=fn_al_tt_1",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u60.png"}},
{
          "id":"1ea5c3cd20014c2d9cc844055361e37e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":510,
              "y":250},
            "size":{
              "width":190,
              "height":273}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"840d260b76ae4b27b9a3e2259d882d96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":510,
                  "y":250},
                "size":{
                  "width":190,
                  "height":273}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt7214954/?ref_=nv_sr_srsg_0 in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt7214954/?ref_=nv_sr_srsg_0",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u66.png"}},
{
          "id":"6c2d3788ef0c4e5e8093c559b79d72d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":588,
              "y":528},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e690093f431411a9629d68b65e9091a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":588,
                  "y":528},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d42cb29cb364dd1b46b3bf85030fc87",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":768,
              "y":250},
            "size":{
              "width":192,
              "height":273}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f67aff2d2e24a0f8397da093863a7ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":768,
                  "y":250},
                "size":{
                  "width":192,
                  "height":273}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt8097030/?ref_=nv_sr_srsg_0 in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt8097030/?ref_=nv_sr_srsg_0",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/animation/u14.png"}},
{
          "id":"5939f74765b34e1a9688763d9fda8c3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":781,
              "y":528},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01b0a9ce592e4b6f94129b43b9f60383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":781,
                  "y":528},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5e833afeacb486ba9c525d30fbcc625",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "horizontalAlignment":"center",
            "location":{
              "x":37,
              "y":865},
            "size":{
              "width":200,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6b5b2950bb44508b8861e3b2075c41c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "horizontalAlignment":"center",
                "location":{
                  "x":37,
                  "y":865},
                "size":{
                  "width":200,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"796289c3f90848aebe39cd461abe2aba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":40,
              "y":590},
            "size":{
              "width":190,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d30dc7086ec94c378e076dd450823e9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":40,
                  "y":590},
                "size":{
                  "width":190,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt8912936/?ref_=nv_sr_srsg_0 in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt8912936/?ref_=nv_sr_srsg_0",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/animation/u20.png"}},
{
          "id":"2c34350754e64d88a8089b02007b5efc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":276,
              "y":591},
            "size":{
              "width":190,
              "height":269}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7d89d31114a476ea27ec37bdeb5038e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":276,
                  "y":591},
                "size":{
                  "width":190,
                  "height":269}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt12412888/?ref_=nv_sr_srsg_0 in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt12412888/?ref_=nv_sr_srsg_0",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/animation/u22.png"}},
{
          "id":"1562dff7a26440168af89459dd484e38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":294,
              "y":865},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3085c8681e754060bf442770a25fd0b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":294,
                  "y":865},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b49bda5e57c44eebf5d9425af12572c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":544,
              "y":865},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8555e624f73416b961f0f988d644efd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":544,
                  "y":865},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c88397b6afd34eaebf91f855918e4533",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":510,
              "y":592},
            "size":{
              "width":190,
              "height":268}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11f3999c03d34cd79d982794c6b9dfe4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":510,
                  "y":592},
                "size":{
                  "width":190,
                  "height":268}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt5181830/?ref_=nv_sr_srsg_0 in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt5181830/?ref_=nv_sr_srsg_0",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/animation/u28.png"}},
{
          "id":"11cc49c1b8844713aed208b9c6d8a9f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "horizontalAlignment":"center",
            "location":{
              "x":765,
              "y":865},
            "size":{
              "width":200,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f244453913514f26a07f473a81de7dd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "horizontalAlignment":"center",
                "location":{
                  "x":765,
                  "y":865},
                "size":{
                  "width":200,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd1df3e148b6430a8684403c3bb4bb85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":768,
              "y":591},
            "size":{
              "width":190,
              "height":269}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12eabbf2db904ea291a25ff48adcaaf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":768,
                  "y":591},
                "size":{
                  "width":190,
                  "height":269}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt3513500/?ref_=nv_sr_srsg_0 in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt3513500/?ref_=nv_sr_srsg_0",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/animation/u32.png"}},
{
          "id":"ba6fed40e58e4c13aebd84e09ef84c73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":77,
              "y":1214},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac4371750842485881a5eabc10a211e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":77,
                  "y":1214},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80fc4d6bbe284c62b32a900f8878a460",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":43,
              "y":930},
            "size":{
              "width":187,
              "height":280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c850e6f9005c4fdbb9a29291a84e14d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":43,
                  "y":930},
                "size":{
                  "width":187,
                  "height":280}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt10687116/?ref_=nv_sr_srsg_0 in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt10687116/?ref_=nv_sr_srsg_0",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/animation/u36.png"}},
{
          "id":"8e78038729b943c0ae012c703f86386d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":280,
              "y":1214},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57b3a3c806174fd98cff94c326c390e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":280,
                  "y":1214},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7eb1c778b546409899a8abee1376ab47",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":276,
              "y":934},
            "size":{
              "width":187,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9c9f955336e4b16b262fb7501421c07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":276,
                  "y":934},
                "size":{
                  "width":187,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt9288748/?ref_=nv_sr_srsg_0 in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt9288748/?ref_=nv_sr_srsg_0",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/animation/u40.png"}},
{
          "id":"f21a6e0225124d4ca3af7afe6b570be1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":510,
              "y":930},
            "size":{
              "width":187,
              "height":280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"febcb64af78e48daa321bd32791e7b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":510,
                  "y":930},
                "size":{
                  "width":187,
                  "height":280}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt8115900/?ref_=nv_sr_srsg_0 in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt8115900/?ref_=nv_sr_srsg_0",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/animation/u42.png"}},
{
          "id":"58dfff394e5f4deebfef9b431a99db3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":544,
              "y":1215},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6f71f1983964cf18b52bd696b56fccb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":544,
                  "y":1215},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41e72b6a4a2742fb99f561f2b37343a0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":768,
              "y":934},
            "size":{
              "width":187,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8282a467c894acea7be649f4a8927aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":768,
                  "y":934},
                "size":{
                  "width":187,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.imdb.com/title/tt10298810/?ref_=nv_sr_srsg_0 in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.imdb.com/title/tt10298810/?ref_=nv_sr_srsg_0",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/animation/u46.png"}},
{
          "id":"3783d4fbd02c45ff9311cb10f12d9c53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Ravie Regular', 'Ravie'",
            "location":{
              "x":800,
              "y":1214},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f9a941638a34fc8acb363e6beedcad3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Ravie Regular', 'Ravie'",
                "location":{
                  "x":800,
                  "y":1214},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de1dd3f262f7448a82ad39fc80d3cbcf",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":384,
              "y":41.5},
            "size":{
              "width":600,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df8690db37f24fc192c23d1ea3d29267",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":600,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8e067ab50a4f454dad21ffefff383f42",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"13fe2b92f0214293a7f31c654eb60660",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Home in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"home.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u72.png"}},
{
                  "id":"cb07a8535f184b3a89a3e06c29edac9e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"74f348fee0c54d978087b4e08e77a169",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Action in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"action.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u72.png"}},
{
                  "id":"f17cc6de6bc14937a5f07b8abb76a39c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a1124ae833294a8f860d44c1fc41f1d1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Comedy in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"comedy.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u72.png"}},
{
                  "id":"fb3b5b9924694e0baaa5f266bc2fd505",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"20523b5f0c8e481bac073f6da7bf4e67",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Horror in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"horror.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u72.png"}},
{
                  "id":"3177d14ad38c46fbbefcad2f98b0ebd0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9c46a53627d4cf8a471f369b9438f19",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Animation in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"animation.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u72.png"}},
{
                  "id":"76241cfcdfb64779a380843c1748b398",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"692e1b621fa040e9b549be7c8a7d12ea",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Romance in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"romance.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u82.png"}}]}]},
{
          "id":"113eeced208445e086dfb4e2bc18b730",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Bernard MT Condensed', 'Bernard MT'",
            "fontSize":"72px",
            "fontWeight":"400",
            "verticalAlignment":"middle",
            "location":{
              "x":41,
              "y":10},
            "size":{
              "width":232,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73d74ec99ce14ea999e37d0be79fa5db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Bernard MT Condensed', 'Bernard MT'",
                "fontSize":"72px",
                "fontWeight":"400",
                "verticalAlignment":"middle",
                "location":{
                  "x":41,
                  "y":10},
                "size":{
                  "width":232,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f16f445c757f4d4ba90454e36b406fff":{
      "scriptId":"u0"},
    "f4be15ce799c44e3a3068953bd1f5866":{
      "scriptId":"u1"},
    "eaf518e3478b4830aa386bef24173db8":{
      "scriptId":"u2"},
    "fa14855dba924dc585d5b91d925b1d33":{
      "scriptId":"u3"},
    "88c60d993fc1467299f22c8d5ab88052":{
      "scriptId":"u4"},
    "9a09ad3bab7b4ff8ba5f471e16c4c7c7":{
      "scriptId":"u5"},
    "080d8f8e60d24679a603deb6f1af664a":{
      "scriptId":"u6"},
    "c9145a021f48472a9963758e8cd9d812":{
      "scriptId":"u7"},
    "7c0b1e84b1d5422a892502ca98d26a37":{
      "scriptId":"u8"},
    "5ae34dafda5f4861ac05171e64f3d339":{
      "scriptId":"u9"},
    "1ea5c3cd20014c2d9cc844055361e37e":{
      "scriptId":"u10"},
    "840d260b76ae4b27b9a3e2259d882d96":{
      "scriptId":"u11"},
    "6c2d3788ef0c4e5e8093c559b79d72d5":{
      "scriptId":"u12"},
    "3e690093f431411a9629d68b65e9091a":{
      "scriptId":"u13"},
    "3d42cb29cb364dd1b46b3bf85030fc87":{
      "scriptId":"u14"},
    "0f67aff2d2e24a0f8397da093863a7ae":{
      "scriptId":"u15"},
    "5939f74765b34e1a9688763d9fda8c3a":{
      "scriptId":"u16"},
    "01b0a9ce592e4b6f94129b43b9f60383":{
      "scriptId":"u17"},
    "d5e833afeacb486ba9c525d30fbcc625":{
      "scriptId":"u18"},
    "e6b5b2950bb44508b8861e3b2075c41c":{
      "scriptId":"u19"},
    "796289c3f90848aebe39cd461abe2aba":{
      "scriptId":"u20"},
    "d30dc7086ec94c378e076dd450823e9b":{
      "scriptId":"u21"},
    "2c34350754e64d88a8089b02007b5efc":{
      "scriptId":"u22"},
    "c7d89d31114a476ea27ec37bdeb5038e":{
      "scriptId":"u23"},
    "1562dff7a26440168af89459dd484e38":{
      "scriptId":"u24"},
    "3085c8681e754060bf442770a25fd0b9":{
      "scriptId":"u25"},
    "1b49bda5e57c44eebf5d9425af12572c":{
      "scriptId":"u26"},
    "f8555e624f73416b961f0f988d644efd":{
      "scriptId":"u27"},
    "c88397b6afd34eaebf91f855918e4533":{
      "scriptId":"u28"},
    "11f3999c03d34cd79d982794c6b9dfe4":{
      "scriptId":"u29"},
    "11cc49c1b8844713aed208b9c6d8a9f9":{
      "scriptId":"u30"},
    "f244453913514f26a07f473a81de7dd7":{
      "scriptId":"u31"},
    "dd1df3e148b6430a8684403c3bb4bb85":{
      "scriptId":"u32"},
    "12eabbf2db904ea291a25ff48adcaaf9":{
      "scriptId":"u33"},
    "ba6fed40e58e4c13aebd84e09ef84c73":{
      "scriptId":"u34"},
    "ac4371750842485881a5eabc10a211e8":{
      "scriptId":"u35"},
    "80fc4d6bbe284c62b32a900f8878a460":{
      "scriptId":"u36"},
    "c850e6f9005c4fdbb9a29291a84e14d2":{
      "scriptId":"u37"},
    "8e78038729b943c0ae012c703f86386d":{
      "scriptId":"u38"},
    "57b3a3c806174fd98cff94c326c390e9":{
      "scriptId":"u39"},
    "7eb1c778b546409899a8abee1376ab47":{
      "scriptId":"u40"},
    "a9c9f955336e4b16b262fb7501421c07":{
      "scriptId":"u41"},
    "f21a6e0225124d4ca3af7afe6b570be1":{
      "scriptId":"u42"},
    "febcb64af78e48daa321bd32791e7b62":{
      "scriptId":"u43"},
    "58dfff394e5f4deebfef9b431a99db3c":{
      "scriptId":"u44"},
    "d6f71f1983964cf18b52bd696b56fccb":{
      "scriptId":"u45"},
    "41e72b6a4a2742fb99f561f2b37343a0":{
      "scriptId":"u46"},
    "c8282a467c894acea7be649f4a8927aa":{
      "scriptId":"u47"},
    "3783d4fbd02c45ff9311cb10f12d9c53":{
      "scriptId":"u48"},
    "5f9a941638a34fc8acb363e6beedcad3":{
      "scriptId":"u49"},
    "de1dd3f262f7448a82ad39fc80d3cbcf":{
      "scriptId":"u50"},
    "df8690db37f24fc192c23d1ea3d29267":{
      "scriptId":"u51"},
    "8e067ab50a4f454dad21ffefff383f42":{
      "scriptId":"u52"},
    "13fe2b92f0214293a7f31c654eb60660":{
      "scriptId":"u53"},
    "cb07a8535f184b3a89a3e06c29edac9e":{
      "scriptId":"u54"},
    "74f348fee0c54d978087b4e08e77a169":{
      "scriptId":"u55"},
    "f17cc6de6bc14937a5f07b8abb76a39c":{
      "scriptId":"u56"},
    "a1124ae833294a8f860d44c1fc41f1d1":{
      "scriptId":"u57"},
    "fb3b5b9924694e0baaa5f266bc2fd505":{
      "scriptId":"u58"},
    "20523b5f0c8e481bac073f6da7bf4e67":{
      "scriptId":"u59"},
    "3177d14ad38c46fbbefcad2f98b0ebd0":{
      "scriptId":"u60"},
    "d9c46a53627d4cf8a471f369b9438f19":{
      "scriptId":"u61"},
    "76241cfcdfb64779a380843c1748b398":{
      "scriptId":"u62"},
    "692e1b621fa040e9b549be7c8a7d12ea":{
      "scriptId":"u63"},
    "113eeced208445e086dfb4e2bc18b730":{
      "scriptId":"u64"},
    "73d74ec99ce14ea999e37d0be79fa5db":{
      "scriptId":"u65"}}});